<?php

/* 
 * Product: PayVector Payment Gateway
 * Version: 1.0.0
 * Release Date: 2014.03.07
 * Note - should not be included directly, please include TransactionProcessor instead as that includes dependencies of this class
 * 
 * Copyright (C) 2014 PayVector <support@payvector.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 
class ISOHelper
{
	public static function getISOCountryList()
	{
		$iclISOCountryList = new ISOCountryList();
		$iclISOCountryList->add(826, "GB", "GBR", "United Kingdom", 3);
		$iclISOCountryList->add(840, "US", "USA", "United States", 2);
		$iclISOCountryList->add(36, "AU", "AUS", "Australia", 1);
		$iclISOCountryList->add(124, "CA", "CAN", "Canada", 1);
		$iclISOCountryList->add(276, "DE", "DEU", "Germany", 1);
		$iclISOCountryList->add(250, "FR", "FRA", "France", 1);
		$iclISOCountryList->add(533, "AW", "ABW", "Aruba", 0);
		$iclISOCountryList->add(4, "AF", "AFG", "Afghanistan", 0);
		$iclISOCountryList->add(24, "AO", "AGO", "Angola", 0);
		$iclISOCountryList->add(660, "AI", "AIA", "Anguilla", 0);
		$iclISOCountryList->add(248, "AX", "ALA", "Åland Islands", 0);
		$iclISOCountryList->add(8, "AL", "ALB", "Albania", 0);
		$iclISOCountryList->add(20, "AD", "AND", "Andorra", 0);
		$iclISOCountryList->add(530, "AN", "ANT", "Netherlands Antilles", 0);
		$iclISOCountryList->add(784, "AE", "ARE", "United Arab Emirates", 0);
		$iclISOCountryList->add(32, "AR", "ARG", "Argentina", 0);
		$iclISOCountryList->add(51, "AM", "ARM", "Armenia", 0);
		$iclISOCountryList->add(16, "AS", "ASM", "American Samoa", 0);
		$iclISOCountryList->add(10, "AQ", "ATA", "Antarctica", 0);
		$iclISOCountryList->add(260, "TF", "ATF", "French Southern Territories", 0);
		$iclISOCountryList->add(28, "AG", "ATG", "Antigua and Barbuda", 0);
		$iclISOCountryList->add(40, "AT", "AUT", "Austria", 0);
		$iclISOCountryList->add(31, "AZ", "AZE", "Azerbaijan", 0);
		$iclISOCountryList->add(108, "BI", "BDI", "Burundi", 0);
		$iclISOCountryList->add(56, "BE", "BEL", "Belgium", 0);
		$iclISOCountryList->add(204, "BJ", "BEN", "Benin", 0);
		$iclISOCountryList->add(854, "BF", "BFA", "Burkina Faso", 0);
		$iclISOCountryList->add(50, "BD", "BGD", "Bangladesh", 0);
		$iclISOCountryList->add(100, "BG", "BGR", "Bulgaria", 0);
		$iclISOCountryList->add(48, "BH", "BHR", "Bahrain", 0);
		$iclISOCountryList->add(44, "BS", "BHS", "Bahamas", 0);
		$iclISOCountryList->add(70, "BA", "BIH", "Bosnia and Herzegovina", 0);
		$iclISOCountryList->add(652, "BL", "BLM", "Saint Barthélemy", 0);
		$iclISOCountryList->add(112, "BY", "BLR", "Belarus", 0);
		$iclISOCountryList->add(84, "BZ", "BLZ", "Belize", 0);
		$iclISOCountryList->add(60, "BM", "BMU", "Bermuda", 0);
		$iclISOCountryList->add(68, "BO", "BOL", "Bolivia", 0);
		$iclISOCountryList->add(76, "BR", "BRA", "Brazil", 0);
		$iclISOCountryList->add(52, "BB", "BRB", "Barbados", 0);
		$iclISOCountryList->add(96, "BN", "BRN", "Brunei Darussalam", 0);
		$iclISOCountryList->add(64, "BT", "BTN", "Bhutan", 0);
		$iclISOCountryList->add(74, "BV", "BVT", "Bouvet Island", 0);
		$iclISOCountryList->add(72, "BW", "BWA", "Botswana", 0);
		$iclISOCountryList->add(140, "CF", "CAF", "Central African Republic", 0);
		$iclISOCountryList->add(166, "CC", "CCK", "Cocos (Keeling) Islands", 0);
		$iclISOCountryList->add(756, "CH", "CHE", "Switzerland", 0);
		$iclISOCountryList->add(152, "CL", "CHL", "Chile", 0);
		$iclISOCountryList->add(156, "CN", "CHN", "China", 0);
		$iclISOCountryList->add(384, "CI", "CIV", "Côte d'Ivoire", 0);
		$iclISOCountryList->add(120, "CM", "CMR", "Cameroon", 0);
		$iclISOCountryList->add(180, "CD", "COD", "Congo,  the Democratic Republic of the", 0);
		$iclISOCountryList->add(178, "CG", "COG", "Congo", 0);
		$iclISOCountryList->add(184, "CK", "COK", "Cook Islands", 0);
		$iclISOCountryList->add(170, "CO", "COL", "Colombia", 0);
		$iclISOCountryList->add(174, "KM", "COM", "Comoros", 0);
		$iclISOCountryList->add(132, "CV", "CPV", "Cape Verde", 0);
		$iclISOCountryList->add(188, "CR", "CRI", "Costa Rica", 0);
		$iclISOCountryList->add(192, "CU", "CUB", "Cuba", 0);
		$iclISOCountryList->add(162, "CX", "CXR", "Christmas Island", 0);
		$iclISOCountryList->add(136, "KY", "CYM", "Cayman Islands", 0);
		$iclISOCountryList->add(196, "CY", "CYP", "Cyprus", 0);
		$iclISOCountryList->add(203, "CZ", "CZE", "Czech Republic", 0);
		$iclISOCountryList->add(262, "DJ", "DJI", "Djibouti", 0);
		$iclISOCountryList->add(212, "DM", "DMA", "Dominica", 0);
		$iclISOCountryList->add(208, "DK", "DNK", "Denmark", 0);
		$iclISOCountryList->add(214, "DO", "DOM", "Dominican Republic", 0);
		$iclISOCountryList->add(12, "DZ", "DZA", "Algeria", 0);
		$iclISOCountryList->add(218, "EC", "ECU", "Ecuador", 0);
		$iclISOCountryList->add(818, "EG", "EGY", "Egypt", 0);
		$iclISOCountryList->add(232, "ER", "ERI", "Eritrea", 0);
		$iclISOCountryList->add(732, "EH", "ESH", "Western Sahara", 0);
		$iclISOCountryList->add(724, "ES", "ESP", "Spain", 0);
		$iclISOCountryList->add(233, "EE", "EST", "Estonia", 0);
		$iclISOCountryList->add(231, "ET", "ETH", "Ethiopia", 0);
		$iclISOCountryList->add(246, "FI", "FIN", "Finland", 0);
		$iclISOCountryList->add(242, "FJ", "FJI", "Fiji", 0);
		$iclISOCountryList->add(238, "FK", "FLK", "Falkland Islands (Malvinas)", 0);
		$iclISOCountryList->add(234, "FO", "FRO", "Faroe Islands", 0);
		$iclISOCountryList->add(583, "FM", "FSM", "Micronesia Federated States of", 0);
		$iclISOCountryList->add(266, "GA", "GAB", "Gabon", 0);
		$iclISOCountryList->add(268, "GE", "GEO", "Georgia", 0);
		$iclISOCountryList->add(831, "GG", "GGY", "Guernsey", 0);
		$iclISOCountryList->add(288, "GH", "GHA", "Ghana", 0);
		$iclISOCountryList->add(292, "GI", "GIB", "Gibraltar", 0);
		$iclISOCountryList->add(324, "GN", "GIN", "Guinea", 0);
		$iclISOCountryList->add(312, "GP", "GLP", "Guadeloupe", 0);
		$iclISOCountryList->add(270, "GM", "GMB", "Gambia", 0);
		$iclISOCountryList->add(624, "GW", "GNB", "Guinea-Bissau", 0);
		$iclISOCountryList->add(226, "GQ", "GNQ", "Equatorial Guinea", 0);
		$iclISOCountryList->add(300, "GR", "GRC", "Greece", 0);
		$iclISOCountryList->add(308, "GD", "GRD", "Grenada", 0);
		$iclISOCountryList->add(304, "GL", "GRL", "Greenland", 0);
		$iclISOCountryList->add(320, "GT", "GTM", "Guatemala", 0);
		$iclISOCountryList->add(254, "GF", "GUF", "French Guiana", 0);
		$iclISOCountryList->add(316, "GU", "GUM", "Guam", 0);
		$iclISOCountryList->add(328, "GY", "GUY", "Guyana", 0);
		$iclISOCountryList->add(344, "HK", "HKG", "Hong Kong", 0);
		$iclISOCountryList->add(334, "HM", "HMD", "Heard Island and McDonald Islands", 0);
		$iclISOCountryList->add(340, "HN", "HND", "Honduras", 0);
		$iclISOCountryList->add(191, "HR", "HRV", "Croatia", 0);
		$iclISOCountryList->add(332, "HT", "HTI", "Haiti", 0);
		$iclISOCountryList->add(348, "HU", "HUN", "Hungary", 0);
		$iclISOCountryList->add(360, "ID", "IDN", "Indonesia", 0);
		$iclISOCountryList->add(833, "IM", "IMN", "Isle of Man", 0);
		$iclISOCountryList->add(356, "IN", "IND", "India", 0);
		$iclISOCountryList->add(86, "IO", "IOT", "British Indian Ocean Territory", 0);
		$iclISOCountryList->add(372, "IE", "IRL", "Ireland", 0);
		$iclISOCountryList->add(364, "IR", "IRN", "Iran Islamic Republic of", 0);
		$iclISOCountryList->add(368, "IQ", "IRQ", "Iraq", 0);
		$iclISOCountryList->add(352, "IS", "ISL", "Iceland", 0);
		$iclISOCountryList->add(376, "IL", "ISR", "Israel", 0);
		$iclISOCountryList->add(380, "IT", "ITA", "Italy", 0);
		$iclISOCountryList->add(388, "JM", "JAM", "Jamaica", 0);
		$iclISOCountryList->add(832, "JE", "JEY", "Jersey", 0);
		$iclISOCountryList->add(400, "JO", "JOR", "Jordan", 0);
		$iclISOCountryList->add(392, "JP", "JPN", "Japan", 0);
		$iclISOCountryList->add(398, "KZ", "KAZ", "Kazakhstan", 0);
		$iclISOCountryList->add(404, "KE", "KEN", "Kenya", 0);
		$iclISOCountryList->add(417, "KG", "KGZ", "Kyrgyzstan", 0);
		$iclISOCountryList->add(116, "KH", "KHM", "Cambodia", 0);
		$iclISOCountryList->add(296, "KI", "KIR", "Kiribati", 0);
		$iclISOCountryList->add(659, "KN", "KNA", "Saint Kitts and Nevis", 0);
		$iclISOCountryList->add(410, "KR", "KOR", "Korea, Republic of", 0);
		$iclISOCountryList->add(414, "KW", "KWT", "Kuwait", 0);
		$iclISOCountryList->add(418, "LA", "LAO", "Lao People's Democratic Republic", 0);
		$iclISOCountryList->add(422, "LB", "LBN", "Lebanon", 0);
		$iclISOCountryList->add(430, "LR", "LBR", "Liberia", 0);
		$iclISOCountryList->add(434, "LY", "LBY", "Libyan Arab Jamahiriya", 0);
		$iclISOCountryList->add(662, "LC", "LCA", "Saint Lucia", 0);
		$iclISOCountryList->add(438, "LI", "LIE", "Liechtenstein", 0);
		$iclISOCountryList->add(144, "LK", "LKA", "Sri Lanka", 0);
		$iclISOCountryList->add(426, "LS", "LSO", "Lesotho", 0);
		$iclISOCountryList->add(440, "LT", "LTU", "Lithuania", 0);
		$iclISOCountryList->add(442, "LU", "LUX", "Luxembourg", 0);
		$iclISOCountryList->add(428, "LV", "LVA", "Latvia", 0);
		$iclISOCountryList->add(446, "MO", "MAC", "Macao", 0);
		$iclISOCountryList->add(663, "MF", "MAF", "Saint Martin (French part)", 0);
		$iclISOCountryList->add(504, "MA", "MAR", "Morocco", 0);
		$iclISOCountryList->add(492, "MC", "MCO", "Monaco", 0);
		$iclISOCountryList->add(498, "MD", "MDA", "Moldova", 0);
		$iclISOCountryList->add(450, "MG", "MDG", "Madagascar", 0);
		$iclISOCountryList->add(462, "MV", "MDV", "Maldives", 0);
		$iclISOCountryList->add(484, "MX", "MEX", "Mexico", 0);
		$iclISOCountryList->add(584, "MH", "MHL", "Marshall Islands", 0);
		$iclISOCountryList->add(807, "MK", "MKD", "Macedonia, the former Yugoslav Republic of", 0);
		$iclISOCountryList->add(466, "ML", "MLI", "Mali", 0);
		$iclISOCountryList->add(470, "MT", "MLT", "Malta", 0);
		$iclISOCountryList->add(104, "MM", "MMR", "Myanmar", 0);
		$iclISOCountryList->add(499, "ME", "MNE", "Montenegro", 0);
		$iclISOCountryList->add(496, "MN", "MNG", "Mongolia", 0);
		$iclISOCountryList->add(580, "MP", "MNP", "Northern Mariana Islands", 0);
		$iclISOCountryList->add(508, "MZ", "MOZ", "Mozambique", 0);
		$iclISOCountryList->add(478, "MR", "MRT", "Mauritania", 0);
		$iclISOCountryList->add(500, "MS", "MSR", "Montserrat", 0);
		$iclISOCountryList->add(474, "MQ", "MTQ", "Martinique", 0);
		$iclISOCountryList->add(480, "MU", "MUS", "Mauritius", 0);
		$iclISOCountryList->add(454, "MW", "MWI", "Malawi", 0);
		$iclISOCountryList->add(458, "MY", "MYS", "Malaysia", 0);
		$iclISOCountryList->add(175, "YT", "MYT", "Mayotte", 0);
		$iclISOCountryList->add(516, "NA", "NAM", "Namibia", 0);
		$iclISOCountryList->add(540, "NC", "NCL", "New Caledonia", 0);
		$iclISOCountryList->add(562, "NE", "NER", "Niger", 0);
		$iclISOCountryList->add(574, "NF", "NFK", "Norfolk Island", 0);
		$iclISOCountryList->add(566, "NG", "NGA", "Nigeria", 0);
		$iclISOCountryList->add(558, "NI", "NIC", "Nicaragua", 0);
		$iclISOCountryList->add(570, "NU", "NIU", "Niue", 0);
		$iclISOCountryList->add(528, "NL", "NLD", "Netherlands", 0);
		$iclISOCountryList->add(578, "NO", "NOR", "Norway", 0);
		$iclISOCountryList->add(524, "NP", "NPL", "Nepal", 0);
		$iclISOCountryList->add(520, "NR", "NRU", "Nauru", 0);
		$iclISOCountryList->add(554, "NZ", "NZL", "New Zealand", 0);
		$iclISOCountryList->add(512, "OM", "OMN", "Oman", 0);
		$iclISOCountryList->add(586, "PK", "PAK", "Pakistan", 0);
		$iclISOCountryList->add(591, "PA", "PAN", "Panama", 0);
		$iclISOCountryList->add(612, "PN", "PCN", "Pitcairn", 0);
		$iclISOCountryList->add(604, "PE", "PER", "Peru", 0);
		$iclISOCountryList->add(608, "PH", "PHL", "Philippines", 0);
		$iclISOCountryList->add(585, "PW", "PLW", "Palau", 0);
		$iclISOCountryList->add(598, "PG", "PNG", "Papua New Guinea", 0);
		$iclISOCountryList->add(616, "PL", "POL", "Poland", 0);
		$iclISOCountryList->add(630, "PR", "PRI", "Puerto Rico", 0);
		$iclISOCountryList->add(408, "KP", "PRK", "Korea, Democratic People's Republic of", 0);
		$iclISOCountryList->add(620, "PT", "PRT", "Portugal", 0);
		$iclISOCountryList->add(600, "PY", "PRY", "Paraguay", 0);
		$iclISOCountryList->add(275, "PS", "PSE", "Palestinian Territory,  Occupied", 0);
		$iclISOCountryList->add(258, "PF", "PYF", "French Polynesia", 0);
		$iclISOCountryList->add(634, "QA", "QAT", "Qatar", 0);
		$iclISOCountryList->add(638, "RE", "REU", "Réunion", 0);
		$iclISOCountryList->add(642, "RO", "ROU", "Romania", 0);
		$iclISOCountryList->add(643, "RU", "RUS", "Russian Federation", 0);
		$iclISOCountryList->add(646, "RW", "RWA", "Rwanda", 0);
		$iclISOCountryList->add(682, "SA", "SAU", "Saudi Arabia", 0);
		$iclISOCountryList->add(736, "SD", "SDN", "Sudan", 0);
		$iclISOCountryList->add(686, "SN", "SEN", "Senegal", 0);
		$iclISOCountryList->add(702, "SG", "SGP", "Singapore", 0);
		$iclISOCountryList->add(239, "GS", "SGS", "South Georgia and the South Sandwich Islands", 0);
		$iclISOCountryList->add(654, "SH", "SHN", "Saint Helena", 0);
		$iclISOCountryList->add(744, "SJ", "SJM", "Svalbard and Jan Mayen", 0);
		$iclISOCountryList->add(90, "SB", "SLB", "Solomon Islands", 0);
		$iclISOCountryList->add(694, "SL", "SLE", "Sierra Leone", 0);
		$iclISOCountryList->add(222, "SV", "SLV", "El Salvador", 0);
		$iclISOCountryList->add(674, "SM", "SMR", "San Marino", 0);
		$iclISOCountryList->add(706, "SO", "SOM", "Somalia", 0);
		$iclISOCountryList->add(666, "PM", "SPM", "Saint Pierre and Miquelon", 0);
		$iclISOCountryList->add(688, "RS", "SRB", "Serbia", 0);
		$iclISOCountryList->add(678, "ST", "STP", "Sao Tome and Principe", 0);
		$iclISOCountryList->add(740, "SR", "SUR", "Suriname", 0);
		$iclISOCountryList->add(703, "SK", "SVK", "Slovakia", 0);
		$iclISOCountryList->add(705, "SI", "SVN", "Slovenia", 0);
		$iclISOCountryList->add(752, "SE", "SWE", "Sweden", 0);
		$iclISOCountryList->add(748, "SZ", "SWZ", "Swaziland", 0);
		$iclISOCountryList->add(690, "SC", "SYC", "Seychelles", 0);
		$iclISOCountryList->add(760, "SY", "SYR", "Syrian Arab Republic", 0);
		$iclISOCountryList->add(796, "TC", "TCA", "Turks and Caicos Islands", 0);
		$iclISOCountryList->add(148, "TD", "TCD", "Chad", 0);
		$iclISOCountryList->add(768, "TG", "TGO", "Togo", 0);
		$iclISOCountryList->add(764, "TH", "THA", "Thailand", 0);
		$iclISOCountryList->add(762, "TJ", "TJK", "Tajikistan", 0);
		$iclISOCountryList->add(772, "TK", "TKL", "Tokelau", 0);
		$iclISOCountryList->add(795, "TM", "TKM", "Turkmenistan", 0);
		$iclISOCountryList->add(626, "TL", "TLS", "Timor-Leste", 0);
		$iclISOCountryList->add(776, "TO", "TON", "Tonga", 0);
		$iclISOCountryList->add(780, "TT", "TTO", "Trinidad and Tobago", 0);
		$iclISOCountryList->add(788, "TN", "TUN", "Tunisia", 0);
		$iclISOCountryList->add(792, "TR", "TUR", "Turkey", 0);
		$iclISOCountryList->add(798, "TV", "TUV", "Tuvalu", 0);
		$iclISOCountryList->add(158, "TW", "TWN", "Taiwan, Province of China", 0);
		$iclISOCountryList->add(834, "TZ", "TZA", "Tanzania, United Republic of", 0);
		$iclISOCountryList->add(800, "UG", "UGA", "Uganda", 0);
		$iclISOCountryList->add(804, "UA", "UKR", "Ukraine", 0);
		$iclISOCountryList->add(581, "UM", "UMI", "United States Minor Outlying Islands", 0);
		$iclISOCountryList->add(858, "UY", "URY", "Uruguay", 0);
		$iclISOCountryList->add(860, "UZ", "UZB", "Uzbekistan", 0);
		$iclISOCountryList->add(336, "VA", "VAT", "Holy See (Vatican City State)", 0);
		$iclISOCountryList->add(670, "VC", "VCT", "Saint Vincent and the Grenadines", 0);
		$iclISOCountryList->add(862, "VE", "VEN", "Venezuela", 0);
		$iclISOCountryList->add(92, "VG", "VGB", "Virgin Islands, British", 0);
		$iclISOCountryList->add(850, "VI", "VIR", "Virgin Islands, U.S.", 0);
		$iclISOCountryList->add(704, "VN", "VNM", "Viet Nam", 0);
		$iclISOCountryList->add(548, "VU", "VUT", "Vanuatu", 0);
		$iclISOCountryList->add(876, "WF", "WLF", "Wallis And Futuna", 0);
		$iclISOCountryList->add(882, "WS", "WSM", "Samoa", 0);
		$iclISOCountryList->add(887, "YE", "YEM", "Yemen", 0);
		$iclISOCountryList->add(710, "ZA", "ZAF", "South Africa", 0);
		$iclISOCountryList->add(894, "ZM", "ZMB", "Zambia", 0);
		$iclISOCountryList->add(826, "ZW", "ZWE", "Zimbabwe", 0);
		$iclISOCountryList->add(535, "BQ", "BES", "Bonaire, Sint Eustatius and Saba", 0);
		$iclISOCountryList->add(531, "CW", "CUW", "Curaçao", 0);
		$iclISOCountryList->add(534, "SX", "SXM", "Sint Maarten (Dutch part)", 0);
		$iclISOCountryList->add(728, "SS", "SSD", "South Sudan", 0);
		return $iclISOCountryList;
	}

	public static function getISOCurrencyList()
	{
		$iclISOCurrencyList = new ISOCurrencyList();
		$iclISOCurrencyList->add(634, "Qatari Rial", "QAR", 2);
		$iclISOCurrencyList->add(566, "Naira", "NGN", 2);
		$iclISOCurrencyList->add(678, "Dobra", "STD", 2);
		$iclISOCurrencyList->add(943, "Metical", "MZN", 2);
		$iclISOCurrencyList->add(826, "Pound Sterling", "GBP", 2);
		$iclISOCurrencyList->add(654, "Saint Helena Pound", "SHP", 2);
		$iclISOCurrencyList->add(704, "Vietnamese ??ng", "VND", 2);
		$iclISOCurrencyList->add(952, "CFA Franc BCEAO", "XOF", 0);
		$iclISOCurrencyList->add(356, "Indian Rupee", "INR", 2);
		$iclISOCurrencyList->add(807, "Denar", "MKD", 2);
		$iclISOCurrencyList->add(959, "Gold (one Troy ounce)", "XAU", 0);
		$iclISOCurrencyList->add(410, "South Korean Won", "KRW", 0);
		$iclISOCurrencyList->add(946, "Romanian New Leu", "RON", 2);
		$iclISOCurrencyList->add(949, "New Turkish Lira", "TRY", 2);
		$iclISOCurrencyList->add(532, "Netherlands Antillian Guilder", "ANG", 2);
		$iclISOCurrencyList->add(788, "Tunisian Dinar", "TND", 3);
		$iclISOCurrencyList->add(646, "Rwanda Franc", "RWF", 0);
		$iclISOCurrencyList->add(504, "Moroccan Dirham", "MAD", 2);
		$iclISOCurrencyList->add(174, "Comoro Franc", "KMF", 0);
		$iclISOCurrencyList->add(484, "Mexican Peso", "MXN", 2);
		$iclISOCurrencyList->add(478, "Ouguiya", "MRO", 2);
		$iclISOCurrencyList->add(233, "Kroon", "EEK", 2);
		$iclISOCurrencyList->add(400, "Jordanian Dinar", "JOD", 3);
		$iclISOCurrencyList->add(292, "Gibraltar pound", "GIP", 2);
		$iclISOCurrencyList->add(690, "Seychelles Rupee", "SCR", 2);
		$iclISOCurrencyList->add(422, "Lebanese Pound", "LBP", 2);
		$iclISOCurrencyList->add(232, "Nakfa", "ERN", 2);
		$iclISOCurrencyList->add(496, "Tugrik", "MNT", 2);
		$iclISOCurrencyList->add(328, "Guyana Dollar", "GYD", 2);
		$iclISOCurrencyList->add(970, "Unidad de Valor Real", "COU", 2);
		$iclISOCurrencyList->add(974, "Belarusian Ruble", "BYR", 0);
		$iclISOCurrencyList->add(608, "Philippine Peso", "PHP", 2);
		$iclISOCurrencyList->add(598, "Kina", "PGK", 2);
		$iclISOCurrencyList->add(951, "East Caribbean Dollar", "XCD", 2);
		$iclISOCurrencyList->add(52, "Barbados Dollar", "BBD", 2);
		$iclISOCurrencyList->add(944, "Azerbaijanian Manat", "AZN", 2);
		$iclISOCurrencyList->add(434, "Libyan Dinar", "LYD", 3);
		$iclISOCurrencyList->add(706, "Somali Shilling", "SOS", 2);
		$iclISOCurrencyList->add(950, "CFA Franc BEAC", "XAF", 0);
		$iclISOCurrencyList->add(840, "US Dollar", "USD", 2);
		$iclISOCurrencyList->add(68, "Boliviano", "BOB", 2);
		$iclISOCurrencyList->add(214, "Dominican Peso", "DOP", 2);
		$iclISOCurrencyList->add(818, "Egyptian Pound", "EGP", 2);
		$iclISOCurrencyList->add(170, "Colombian Peso", "COP", 2);
		$iclISOCurrencyList->add(986, "Brazilian Real", "BRL", 2);
		$iclISOCurrencyList->add(961, "Silver (one Troy ounce)", "XAG", 0);
		$iclISOCurrencyList->add(973, "Kwanza", "AOA", 2);
		$iclISOCurrencyList->add(962, "Platinum (one Troy ounce)", "XPT", 0);
		$iclISOCurrencyList->add(414, "Kuwaiti Dinar", "KWD", 3);
		$iclISOCurrencyList->add(604, "Nuevo Sol", "PEN", 2);
		$iclISOCurrencyList->add(702, "Singapore Dollar", "SGD", 2);
		$iclISOCurrencyList->add(862, "Venezuelan bol�var", "VEB", 2);
		$iclISOCurrencyList->add(953, "CFP franc", "XPF", 0);
		$iclISOCurrencyList->add(558, "Cordoba Oro", "NIO", 2);
		$iclISOCurrencyList->add(348, "Forint", "HUF", 2);
		$iclISOCurrencyList->add(948, "WIR Franc ", "CHW", 2);
		$iclISOCurrencyList->add(116, "Riel", "KHR", 2);
		$iclISOCurrencyList->add(956, "European Monetary Unit", "XBB", 0);
		$iclISOCurrencyList->add(156, "Yuan Renminbi", "CNY", 2);
		$iclISOCurrencyList->add(834, "Tanzanian Shilling", "TZS", 2);
		$iclISOCurrencyList->add(997, "", "USN", 2);
		$iclISOCurrencyList->add(981, "Lari", "GEL", 2);
		$iclISOCurrencyList->add(242, "Fiji Dollar", "FJD", 2);
		$iclISOCurrencyList->add(941, "Serbian Dinar", "RSD", 2);
		$iclISOCurrencyList->add(104, "Kyat", "MMK", 2);
		$iclISOCurrencyList->add(84, " Belize Dollar", "BZD", 2);
		$iclISOCurrencyList->add(710, "South African Rand", "ZAR", 2);
		$iclISOCurrencyList->add(760, "Syrian Pound", "SYP", 2);
		$iclISOCurrencyList->add(512, "Rial Omani", "OMR", 3);
		$iclISOCurrencyList->add(324, "Guinea Franc", "GNF", 0);
		$iclISOCurrencyList->add(196, "Cyprus Pound", "CYP", 2);
		$iclISOCurrencyList->add(960, "Special Drawing Rights", "XDR", 0);
		$iclISOCurrencyList->add(716, "Zimbabwe Dollar", "ZWD", 2);
		$iclISOCurrencyList->add(972, "Somoni", "TJS", 2);
		$iclISOCurrencyList->add(462, "Rufiyaa", "MVR", 2);
		$iclISOCurrencyList->add(979, "Mexican Unidad de Inversion (UDI)", "MXV", 2);
		$iclISOCurrencyList->add(860, "Uzbekistan Som", "UZS", 2);
		$iclISOCurrencyList->add(12, "Algerian Dinar", "DZD", 2);
		$iclISOCurrencyList->add(332, "Haiti Gourde", "HTG", 2);
		$iclISOCurrencyList->add(963, "Code reserved for testing purposes", "XTS", 0);
		$iclISOCurrencyList->add(32, "Argentine Peso", "ARS", 2);
		$iclISOCurrencyList->add(642, "Romanian Leu", "ROL", 2);
		$iclISOCurrencyList->add(984, "Bolivian Mvdol (Funds code)", "BOV", 2);
		$iclISOCurrencyList->add(440, "Lithuanian Litas", "LTL", 2);
		$iclISOCurrencyList->add(480, "Mauritius Rupee", "MUR", 2);
		$iclISOCurrencyList->add(426, "Loti", "LSL", 2);
		$iclISOCurrencyList->add(262, "Djibouti Franc", "DJF", 0);
		$iclISOCurrencyList->add(886, "Yemeni Rial", "YER", 2);
		$iclISOCurrencyList->add(748, "Lilangeni", "SZL", 2);
		$iclISOCurrencyList->add(192, "Cuban Peso", "CUP", 2);
		$iclISOCurrencyList->add(548, "Vatu", "VUV", 0);
		$iclISOCurrencyList->add(360, "Rupiah", "IDR", 2);
		$iclISOCurrencyList->add(51, "Armenian Dram", "AMD", 2);
		$iclISOCurrencyList->add(894, "Kwacha", "ZMK", 2);
		$iclISOCurrencyList->add(90, "Solomon Islands Dollar", "SBD", 2);
		$iclISOCurrencyList->add(132, "Cape Verde Escudo", "CVE", 2);
		$iclISOCurrencyList->add(999, "No currency", "XXX", 0);
		$iclISOCurrencyList->add(524, "Nepalese Rupee", "NPR", 2);
		$iclISOCurrencyList->add(203, "Czech Koruna", "CZK", 2);
		$iclISOCurrencyList->add(44, "Bahamian Dollar", "BSD", 2);
		$iclISOCurrencyList->add(96, "Brunei Dollar", "BND", 2);
		$iclISOCurrencyList->add(50, "Bangladeshi Taka", "BDT", 2);
		$iclISOCurrencyList->add(404, "Kenyan Shilling", "KES", 2);
		$iclISOCurrencyList->add(947, "WIR Euro ", "CHE", 2);
		$iclISOCurrencyList->add(964, "Palladium (one Troy ounce)", "XPD", 0);
		$iclISOCurrencyList->add(398, "Tenge", "KZT", 2);
		$iclISOCurrencyList->add(352, "Iceland Krona", "ISK", 2);
		$iclISOCurrencyList->add(64, "Ngultrum", "BTN", 2);
		$iclISOCurrencyList->add(533, "Aruban Guilder", "AWG", 2);
		$iclISOCurrencyList->add(230, "Ethiopian Birr", "ETB", 2);
		$iclISOCurrencyList->add(800, "Uganda Shilling", "UGX", 2);
		$iclISOCurrencyList->add(968, "Surinam Dollar", "SRD", 2);
		$iclISOCurrencyList->add(882, "Samoan Tala", "WST", 2);
		$iclISOCurrencyList->add(454, "Kwacha", "MWK", 2);
		$iclISOCurrencyList->add(985, "Zloty", "PLN", 2);
		$iclISOCurrencyList->add(124, "Canadian Dollar", "CAD", 2);
		$iclISOCurrencyList->add(776, "Pa'anga", "TOP", 2);
		$iclISOCurrencyList->add(208, "Danish Krone", "DKK", 2);
		$iclISOCurrencyList->add(108, "Burundian Franc", "BIF", 0);
		$iclISOCurrencyList->add(764, "Baht", "THB", 2);
		$iclISOCurrencyList->add(458, "Malaysian Ringgit", "MYR", 2);
		$iclISOCurrencyList->add(364, "Iranian Rial", "IRR", 2);
		$iclISOCurrencyList->add(600, "Guarani", "PYG", 0);
		$iclISOCurrencyList->add(977, "Convertible Marks", "BAM", 2);
		$iclISOCurrencyList->add(446, "Pataca", "MOP", 2);
		$iclISOCurrencyList->add(780, "Trinidad and Tobago Dollar", "TTD", 2);
		$iclISOCurrencyList->add(703, "Slovak Koruna", "SKK", 2);
		$iclISOCurrencyList->add(958, "European Unit of Account 17 (E.U.A.-17)", "XBD", 0);
		$iclISOCurrencyList->add(430, "Liberian Dollar", "LRD", 2);
		$iclISOCurrencyList->add(191, "Croatian Kuna", "HRK", 2);
		$iclISOCurrencyList->add(694, "Leone", "SLL", 2);
		$iclISOCurrencyList->add(756, "Swiss Franc", "CHF", 2);
		$iclISOCurrencyList->add(969, "Malagasy Ariary", "MGA", 0);
		$iclISOCurrencyList->add(270, "Dalasi", "GMD", 2);
		$iclISOCurrencyList->add(418, "Kip", "LAK", 2);
		$iclISOCurrencyList->add(516, "Namibian Dollar", "NAD", 2);
		$iclISOCurrencyList->add(392, "Japanese yen", "JPY", 0);
		$iclISOCurrencyList->add(320, "Quetzal", "GTQ", 2);
		$iclISOCurrencyList->add(554, "New Zealand Dollar", "NZD", 2);
		$iclISOCurrencyList->add(578, "Norwegian Krone", "NOK", 2);
		$iclISOCurrencyList->add(376, "New Israeli Shekel", "ILS", 2);
		$iclISOCurrencyList->add(957, "European Unit of Account 9 (E.U.A.-9)", "XBC", 0);
		$iclISOCurrencyList->add(498, "Moldovan Leu", "MDL", 2);
		$iclISOCurrencyList->add(998, "", "USS", 2);
		$iclISOCurrencyList->add(955, "European Composite Unit (EURCO)", "XBA", 0);
		$iclISOCurrencyList->add(344, "Hong Kong Dollar", "HKD", 2);
		$iclISOCurrencyList->add(417, "Som", "KGS", 2);
		$iclISOCurrencyList->add(858, "Peso Uruguayo", "UYU", 2);
		$iclISOCurrencyList->add(60, "Bermudian Dollar ", "BMD", 2);
		$iclISOCurrencyList->add(682, "Saudi Riyal", "SAR", 2);
		$iclISOCurrencyList->add(643, "Russian Ruble", "RUB", 2);
		$iclISOCurrencyList->add(470, "Maltese Lira", "MTL", 2);
		$iclISOCurrencyList->add(340, "Lempira", "HNL", 2);
		$iclISOCurrencyList->add(72, "Pula", "BWP", 2);
		$iclISOCurrencyList->add(368, "Iraqi Dinar", "IQD", 3);
		$iclISOCurrencyList->add(188, "Costa Rican Colon", "CRC", 2);
		$iclISOCurrencyList->add(144, "Sri Lanka Rupee", "LKR", 2);
		$iclISOCurrencyList->add(752, "Swedish Krona", "SEK", 2);
		$iclISOCurrencyList->add(136, "Cayman Islands Dollar", "KYD", 2);
		$iclISOCurrencyList->add(8, "Lek", "ALL", 2);
		$iclISOCurrencyList->add(48, "Bahraini Dinar", "BHD", 3);
		$iclISOCurrencyList->add(795, "Manat", "TMM", 2);
		$iclISOCurrencyList->add(938, "Sudanese Pound", "SDG", 2);
		$iclISOCurrencyList->add(590, "Balboa", "PAB", 2);
		$iclISOCurrencyList->add(152, "Chilean Peso", "CLP", 0);
		$iclISOCurrencyList->add(980, "Hryvnia", "UAH", 2);
		$iclISOCurrencyList->add(428, "Latvian Lats", "LVL", 2);
		$iclISOCurrencyList->add(288, "Cedi", "GHS", 2);
		$iclISOCurrencyList->add(978, "Euro", "EUR", 2);
		$iclISOCurrencyList->add(976, "Franc Congolais", "CDF", 2);
		$iclISOCurrencyList->add(586, "Pakistan Rupee", "PKR", 2);
		$iclISOCurrencyList->add(408, "North Korean Won", "KPW", 2);
		$iclISOCurrencyList->add(388, "Jamaican Dollar", "JMD", 2);
		$iclISOCurrencyList->add(990, "Unidades de formento", "CLF", 0);
		$iclISOCurrencyList->add(971, "Afghani", "AFN", 2);
		$iclISOCurrencyList->add(975, "Bulgarian Lev", "BGN", 2);
		$iclISOCurrencyList->add(36, "Australian Dollar", "AUD", 2);
		$iclISOCurrencyList->add(238, "Falkland Islands Pound", "FKP", 2);
		$iclISOCurrencyList->add(901, "New Taiwan Dollar", "TWD", 2);
		$iclISOCurrencyList->add(784, "United Arab Emirates dirham", "AED", 2);
		return $iclISOCurrencyList;
	}	
}	