<?php
$blockdata = $block->getData('blockdata');
$formAction = isset($blockdata['FormAction']) ? $blockdata['FormAction'] : '';
$formAttributes = isset($blockdata['FormAttributes']) ? $blockdata['FormAttributes'] : '';
$params = isset($blockdata['params']) ? $blockdata['params'] : [];
?>
<form method="POST" id="form_auth3d" name="form_auth3d" action="<?php echo htmlspecialchars($formAction, ENT_QUOTES, 'UTF-8'); ?>" <?php echo $formAttributes; ?>>
        <?php foreach ($params as $key => $value): ?>
            <input type="hidden" name="<?php echo htmlspecialchars($key, ENT_QUOTES, 'UTF-8'); ?>" value="<?php echo htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); ?>">
        <?php endforeach; ?>
    </form>
</form>

<script>
    var frm = document.getElementById("form_auth3d");
    frm.submit();
</script>