<?php

/* 
 * Product: PayVector Payment Gateway
 * Version: 1.0.0
 * Release Date: 2014.03.07
 * Note - should not be included directly, please include TransactionProcessor instead as that includes dependencies of this class
 * 
 * Copyright (C) 2014 PayVector <support@payvector.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Opencart\Catalog\Controller\Extension\Payvector\Payment;

class ISOHelper
{
	/**
	 * @return ISOCountryList
	 */
	public static function getISOCountryList()
	{
		$iclISOCountryList = new \net\thepaymentgateway\common\ISOCountryList();
		$iclISOCountryList->add(826, "United Kingdom", "GB", 3);
		$iclISOCountryList->add(840, "United States", "US", 2);
		$iclISOCountryList->add(36, "Australia", "AU", 1);
		$iclISOCountryList->add(124, "Canada", "CA", 1);
		$iclISOCountryList->add(276, "Germany", "DE", 1);
		$iclISOCountryList->add(250, "France", "FR", 1);
		$iclISOCountryList->add(533, "Aruba", "AW", 0);
		$iclISOCountryList->add(4, "Afghanistan", "AF", 0);
		$iclISOCountryList->add(24, "Angola", "AO", 0);
		$iclISOCountryList->add(660, "Anguilla", "AI", 0);
		$iclISOCountryList->add(248, "Åland Islands", "AX", 0);
		$iclISOCountryList->add(8, "Albania", "AL", 0);
		$iclISOCountryList->add(20, "Andorra", "AD", 0);
		$iclISOCountryList->add(530, "Netherlands Antilles", "AN", 0);
		$iclISOCountryList->add(784, "United Arab Emirates", "AE", 0);
		$iclISOCountryList->add(32, "Argentina", "AR", 0);
		$iclISOCountryList->add(51, "Armenia", "AM", 0);
		$iclISOCountryList->add(16, "American Samoa", "AS", 0);
		$iclISOCountryList->add(10, "Antarctica", "AQ", 0);
		$iclISOCountryList->add(260, "French Southern Territories", "TF", 0);
		$iclISOCountryList->add(28, "Antigua and Barbuda", "AG", 0);
		$iclISOCountryList->add(40, "Austria", "AT", 0);
		$iclISOCountryList->add(31, "Azerbaijan", "AZ", 0);
		$iclISOCountryList->add(108, "Burundi", "BI", 0);
		$iclISOCountryList->add(56, "Belgium", "BE", 0);
		$iclISOCountryList->add(204, "Benin", "BJ", 0);
		$iclISOCountryList->add(854, "Burkina Faso", "BF", 0);
		$iclISOCountryList->add(50, "Bangladesh", "BD", 0);
		$iclISOCountryList->add(100, "Bulgaria", "BG", 0);
		$iclISOCountryList->add(48, "Bahrain", "BH", 0);
		$iclISOCountryList->add(44, "Bahamas", "BS", 0);
		$iclISOCountryList->add(70, "Bosnia and Herzegovina", "BA", 0);
		$iclISOCountryList->add(652, "Saint Barthélemy", "BL", 0);
		$iclISOCountryList->add(112, "Belarus", "BY", 0);
		$iclISOCountryList->add(84, "Belize", "BZ", 0);
		$iclISOCountryList->add(60, "Bermuda", "BM", 0);
		$iclISOCountryList->add(68, "Bolivia", "BO", 0);
		$iclISOCountryList->add(76, "Brazil", "BR", 0);
		$iclISOCountryList->add(52, "Barbados", "BB", 0);
		$iclISOCountryList->add(96, "Brunei Darussalam", "BN", 0);
		$iclISOCountryList->add(64, "Bhutan", "BT", 0);
		$iclISOCountryList->add(74, "Bouvet Island", "BV", 0);
		$iclISOCountryList->add(72, "Botswana", "BW", 0);
		$iclISOCountryList->add(140, "Central African Republic", "CF", 0);
		$iclISOCountryList->add(166, "Cocos (Keeling) Islands", "CC", 0);
		$iclISOCountryList->add(756, "Switzerland", "CH", 0);
		$iclISOCountryList->add(152, "Chile", "CL", 0);
		$iclISOCountryList->add(156, "China", "CN", 0);
		$iclISOCountryList->add(384, "Côte d'Ivoire", "CI", 0);
		$iclISOCountryList->add(120, "Cameroon", "CM", 0);
		$iclISOCountryList->add(180, "Congo, the Democratic Republic of the", "CD", 0);
		$iclISOCountryList->add(178, "Congo", "CG", 0);
		$iclISOCountryList->add(184, "Cook Islands", "CK", 0);
		$iclISOCountryList->add(170, "Colombia", "CO", 0);
		$iclISOCountryList->add(174, "Comoros", "KM", 0);
		$iclISOCountryList->add(132, "Cape Verde", "CV", 0);
		$iclISOCountryList->add(188, "Costa Rica", "CR", 0);
		$iclISOCountryList->add(192, "Cuba", "CU", 0);
		$iclISOCountryList->add(162, "Christmas Island", "CX", 0);
		$iclISOCountryList->add(136, "Cayman Islands", "KY", 0);
		$iclISOCountryList->add(196, "Cyprus", "CY", 0);
		$iclISOCountryList->add(203, "Czech Republic", "CZ", 0);
		$iclISOCountryList->add(262, "Djibouti", "DJ", 0);
		$iclISOCountryList->add(212, "Dominica", "DM", 0);
		$iclISOCountryList->add(208, "Denmark", "DK", 0);
		$iclISOCountryList->add(214, "Dominican Republic", "DO", 0);
		$iclISOCountryList->add(12, "Algeria", "DZ", 0);
		$iclISOCountryList->add(218, "Ecuador", "EC", 0);
		$iclISOCountryList->add(818, "Egypt", "EG", 0);
		$iclISOCountryList->add(232, "Eritrea", "ER", 0);
		$iclISOCountryList->add(732, "Western Sahara", "EH", 0);
		$iclISOCountryList->add(724, "Spain", "ES", 0);
		$iclISOCountryList->add(233, "Estonia", "EE", 0);
		$iclISOCountryList->add(231, "Ethiopia", "ET", 0);
		$iclISOCountryList->add(246, "Finland", "FI", 0);
		$iclISOCountryList->add(242, "Fiji", "FJ", 0);
		$iclISOCountryList->add(238, "Falkland Islands (Malvinas)", "FK", 0);
		$iclISOCountryList->add(234, "Faroe Islands", "FO", 0);
		$iclISOCountryList->add(583, "Micronesia Federated States of", "FM", 0);
		$iclISOCountryList->add(266, "Gabon", "GA", 0);
		$iclISOCountryList->add(268, "Georgia", "GE", 0);
		$iclISOCountryList->add(831, "Guernsey", "GG", 0);
		$iclISOCountryList->add(288, "Ghana", "GH", 0);
		$iclISOCountryList->add(292, "Gibraltar", "GI", 0);
		$iclISOCountryList->add(324, "Guinea", "GN", 0);
		$iclISOCountryList->add(312, "Guadeloupe", "GP", 0);
		$iclISOCountryList->add(270, "Gambia", "GM", 0);
		$iclISOCountryList->add(624, "Guinea-Bissau", "GW", 0);
		$iclISOCountryList->add(226, "Equatorial Guinea", "GQ", 0);
		$iclISOCountryList->add(300, "Greece", "GR", 0);
		$iclISOCountryList->add(308, "Grenada", "GD", 0);
		$iclISOCountryList->add(304, "Greenland", "GL", 0);
		$iclISOCountryList->add(320, "Guatemala", "GT", 0);
		$iclISOCountryList->add(254, "French Guiana", "GF", 0);
		$iclISOCountryList->add(316, "Guam", "GU", 0);
		$iclISOCountryList->add(328, "Guyana", "GY", 0);
		$iclISOCountryList->add(344, "Hong Kong", "HK", 0);
		$iclISOCountryList->add(334, "Heard Island and McDonald Islands", "HM", 0);
		$iclISOCountryList->add(340, "Honduras", "HN", 0);
		$iclISOCountryList->add(191, "Croatia", "HR", 0);
		$iclISOCountryList->add(332, "Haiti", "HT", 0);
		$iclISOCountryList->add(348, "Hungary", "HU", 0);
		$iclISOCountryList->add(360, "Indonesia", "ID", 0);
		$iclISOCountryList->add(833, "Isle of Man", "IM", 0);
		$iclISOCountryList->add(356, "India", "IN", 0);
		$iclISOCountryList->add(86, "British Indian Ocean Territory", "IO", 0);
		$iclISOCountryList->add(372, "Ireland", "IE", 0);
		$iclISOCountryList->add(364, "Iran Islamic Republic of", "IR", 0);
		$iclISOCountryList->add(368, "Iraq", "IQ", 0);
		$iclISOCountryList->add(352, "Iceland", "IS", 0);
		$iclISOCountryList->add(376, "Israel", "IL", 0);
		$iclISOCountryList->add(380, "Italy", "IT", 0);
		$iclISOCountryList->add(388, "Jamaica", "JM", 0);
		$iclISOCountryList->add(832, "Jersey", "JE", 0);
		$iclISOCountryList->add(400, "Jordan", "JO", 0);
		$iclISOCountryList->add(392, "Japan", "JP", 0);
		$iclISOCountryList->add(398, "Kazakhstan", "KZ", 0);
		$iclISOCountryList->add(404, "Kenya", "KE", 0);
		$iclISOCountryList->add(417, "Kyrgyzstan", "KG", 0);
		$iclISOCountryList->add(116, "Cambodia", "KH", 0);
		$iclISOCountryList->add(296, "Kiribati", "KI", 0);
		$iclISOCountryList->add(659, "Saint Kitts and Nevis", "KN", 0);
		$iclISOCountryList->add(410, "Korea, Republic of", "KR", 0);
		$iclISOCountryList->add(414, "Kuwait", "KW", 0);
		$iclISOCountryList->add(418, "Lao People's Democratic Republic", "LA", 0);
		$iclISOCountryList->add(422, "Lebanon", "LB", 0);
		$iclISOCountryList->add(430, "Liberia", "LR", 0);
		$iclISOCountryList->add(434, "Libyan Arab Jamahiriya", "LY", 0);
		$iclISOCountryList->add(662, "Saint Lucia", "LC", 0);
		$iclISOCountryList->add(438, "Liechtenstein", "LI", 0);
		$iclISOCountryList->add(144, "Sri Lanka", "LK", 0);
		$iclISOCountryList->add(426, "Lesotho", "LS", 0);
		$iclISOCountryList->add(440, "Lithuania", "LT", 0);
		$iclISOCountryList->add(442, "Luxembourg", "LU", 0);
		$iclISOCountryList->add(428, "Latvia", "LV", 0);
		$iclISOCountryList->add(446, "Macao", "MO", 0);
		$iclISOCountryList->add(663, "Saint Martin (French part)", "MF", 0);
		$iclISOCountryList->add(504, "Morocco", "MA", 0);
		$iclISOCountryList->add(492, "Monaco", "MC", 0);
		$iclISOCountryList->add(498, "Moldova", "MD", 0);
		$iclISOCountryList->add(450, "Madagascar", "MG", 0);
		$iclISOCountryList->add(462, "Maldives", "MV", 0);
		$iclISOCountryList->add(484, "Mexico", "MX", 0);
		$iclISOCountryList->add(584, "Marshall Islands", "MH", 0);
		$iclISOCountryList->add(807, "Macedonia, the former Yugoslav Republic of", "MK", 0);
		$iclISOCountryList->add(466, "Mali", "ML", 0);
		$iclISOCountryList->add(470, "Malta", "MT", 0);
		$iclISOCountryList->add(104, "Myanmar", "MM", 0);
		$iclISOCountryList->add(499, "Montenegro", "ME", 0);
		$iclISOCountryList->add(496, "Mongolia", "MN", 0);
		$iclISOCountryList->add(580, "Northern Mariana Islands", "MP", 0);
		$iclISOCountryList->add(508, "Mozambique", "MZ", 0);
		$iclISOCountryList->add(478, "Mauritania", "MR", 0);
		$iclISOCountryList->add(500, "Montserrat", "MS", 0);
		$iclISOCountryList->add(474, "Martinique", "MQ", 0);
		$iclISOCountryList->add(480, "Mauritius", "MU", 0);
		$iclISOCountryList->add(454, "Malawi", "MW", 0);
		$iclISOCountryList->add(458, "Malaysia", "MY", 0);
		$iclISOCountryList->add(175, "Mayotte", "YT", 0);
		$iclISOCountryList->add(516, "Namibia", "NA", 0);
		$iclISOCountryList->add(540, "New Caledonia", "NC", 0);
		$iclISOCountryList->add(562, "Niger", "NE", 0);
		$iclISOCountryList->add(574, "Norfolk Island", "NF", 0);
		$iclISOCountryList->add(566, "Nigeria", "NG", 0);
		$iclISOCountryList->add(558, "Nicaragua", "NI", 0);
		$iclISOCountryList->add(570, "Niue", "NU", 0);
		$iclISOCountryList->add(528, "Netherlands", "NL", 0);
		$iclISOCountryList->add(578, "Norway", "NO", 0);
		$iclISOCountryList->add(524, "Nepal", "NP", 0);
		$iclISOCountryList->add(520, "Nauru", "NR", 0);
		$iclISOCountryList->add(554, "New Zealand", "NZ", 0);
		$iclISOCountryList->add(512, "Oman", "OM", 0);
		$iclISOCountryList->add(586, "Pakistan", "PK", 0);
		$iclISOCountryList->add(591, "Panama", "PA", 0);
		$iclISOCountryList->add(612, "Pitcairn", "PN", 0);
		$iclISOCountryList->add(604, "Peru", "PE", 0);
		$iclISOCountryList->add(608, "Philippines", "PH", 0);
		$iclISOCountryList->add(585, "Palau", "PW", 0);
		$iclISOCountryList->add(598, "Papua New Guinea", "PG", 0);
		$iclISOCountryList->add(616, "Poland", "PL", 0);
		$iclISOCountryList->add(630, "Puerto Rico", "PR", 0);
		$iclISOCountryList->add(408, "Korea, Democratic People's Republic of", "KP", 0);
		$iclISOCountryList->add(620, "Portugal", "PT", 0);
		$iclISOCountryList->add(600, "Paraguay", "PY", 0);
		$iclISOCountryList->add(275, "Palestinian Territory, Occupied", "PS", 0);
		$iclISOCountryList->add(258, "French Polynesia", "PF", 0);
		$iclISOCountryList->add(634, "Qatar", "QA", 0);
		$iclISOCountryList->add(638, "Réunion", "RE", 0);
		$iclISOCountryList->add(642, "Romania", "RO", 0);
		$iclISOCountryList->add(643, "Russian Federation", "RU", 0);
		$iclISOCountryList->add(646, "Rwanda", "RW", 0);
		$iclISOCountryList->add(682, "Saudi Arabia", "SA", 0);
		$iclISOCountryList->add(736, "Sudan", "SD", 0);
		$iclISOCountryList->add(686, "Senegal", "SN", 0);
		$iclISOCountryList->add(702, "Singapore", "SG", 0);
		$iclISOCountryList->add(239, "South Georgia and the South Sandwich Islands", "GS", 0);
		$iclISOCountryList->add(654, "Saint Helena", "SH", 0);
		$iclISOCountryList->add(744, "Svalbard and Jan Mayen", "SJ", 0);
		$iclISOCountryList->add(90, "Solomon Islands", "SB", 0);
		$iclISOCountryList->add(694, "Sierra Leone", "SL", 0);
		$iclISOCountryList->add(222, "El Salvador", "SV", 0);
		$iclISOCountryList->add(674, "San Marino", "SM", 0);
		$iclISOCountryList->add(706, "Somalia", "SO", 0);
		$iclISOCountryList->add(666, "Saint Pierre and Miquelon", "PM", 0);
		$iclISOCountryList->add(688, "Serbia", "RS", 0);
		$iclISOCountryList->add(678, "Sao Tome and Principe", "ST", 0);
		$iclISOCountryList->add(740, "Suriname", "SR", 0);
		$iclISOCountryList->add(703, "Slovakia", "SK", 0);
		$iclISOCountryList->add(705, "Slovenia", "SI", 0);
		$iclISOCountryList->add(752, "Sweden", "SE", 0);
		$iclISOCountryList->add(748, "Swaziland", "SZ", 0);
		$iclISOCountryList->add(690, "Seychelles", "SC", 0);
		$iclISOCountryList->add(760, "Syrian Arab Republic", "SY", 0);
		$iclISOCountryList->add(796, "Turks and Caicos Islands", "TC", 0);
		$iclISOCountryList->add(148, "Chad", "TD", 0);
		$iclISOCountryList->add(768, "Togo", "TG", 0);
		$iclISOCountryList->add(764, "Thailand", "TH", 0);
		$iclISOCountryList->add(762, "Tajikistan", "TJ", 0);
		$iclISOCountryList->add(772, "Tokelau", "TK", 0);
		$iclISOCountryList->add(795, "Turkmenistan", "TM", 0);
		$iclISOCountryList->add(626, "Timor-Leste", "TL", 0);
		$iclISOCountryList->add(776, "Tonga", "TO", 0);
		$iclISOCountryList->add(780, "Trinidad and Tobago", "TT", 0);
		$iclISOCountryList->add(788, "Tunisia", "TN", 0);
		$iclISOCountryList->add(792, "Turkey", "TR", 0);
		$iclISOCountryList->add(798, "Tuvalu", "TV", 0);
		$iclISOCountryList->add(158, "Taiwan, Province of China", "TW", 0);
		$iclISOCountryList->add(834, "Tanzania, United Republic of", "TZ", 0);
		$iclISOCountryList->add(800, "Uganda", "UG", 0);
		$iclISOCountryList->add(804, "Ukraine", "UA", 0);
		$iclISOCountryList->add(581, "United States Minor Outlying Islands", "UM", 0);
		$iclISOCountryList->add(858, "Uruguay", "UY", 0);
		$iclISOCountryList->add(860, "Uzbekistan", "UZ", 0);
		$iclISOCountryList->add(336, "Holy See (Vatican City State)", "VA", 0);
		$iclISOCountryList->add(670, "Saint Vincent and the Grenadines", "VC", 0);
		$iclISOCountryList->add(862, "Venezuela", "VE", 0);
		$iclISOCountryList->add(92, "Virgin Islands, British", "VG", 0);
		$iclISOCountryList->add(850, "Virgin Islands, U.S.", "VI", 0);
		$iclISOCountryList->add(704, "Viet Nam", "VN", 0);
		$iclISOCountryList->add(548, "Vanuatu", "VU", 0);
		$iclISOCountryList->add(876, "Wallis And Futuna", "WF", 0);
		$iclISOCountryList->add(882, "Samoa", "WS", 0);
		$iclISOCountryList->add(887, "Yemen", "YE", 0);
		$iclISOCountryList->add(710, "South Africa", "ZA", 0);
		$iclISOCountryList->add(894, "Zambia", "ZM", 0);
		$iclISOCountryList->add(826, "Zimbabwe", "ZW", 0);
		$iclISOCountryList->add(535, "Bonaire, Sint Eustatius and Saba", "BQ", 0);
		$iclISOCountryList->add(531, "Curaçao", "CW", 0);
		$iclISOCountryList->add(534, "Sint Maarten (Dutch part)", "SX", 0);
		$iclISOCountryList->add(728, "South Sudan", "SS", 0);
		return $iclISOCountryList;
	}

	/**
	 * @return ISOCurrencyList
	 */
	public static function getISOCurrencyList()
	{
		$iclISOCurrencyList = new \net\thepaymentgateway\common\ISOCurrencyList();
		$iclISOCurrencyList->add(634, "Qatari Rial", "QAR", 2);
		$iclISOCurrencyList->add(566, "Naira", "NGN", 2);
		$iclISOCurrencyList->add(678, "Dobra", "STD", 2);
		$iclISOCurrencyList->add(943, "Metical", "MZN", 2);
		$iclISOCurrencyList->add(826, "Pound Sterling", "GBP", 2);
		$iclISOCurrencyList->add(654, "Saint Helena Pound", "SHP", 2);
		$iclISOCurrencyList->add(704, "Vietnamese ??ng", "VND", 2);
		$iclISOCurrencyList->add(952, "CFA Franc BCEAO", "XOF", 0);
		$iclISOCurrencyList->add(356, "Indian Rupee", "INR", 2);
		$iclISOCurrencyList->add(807, "Denar", "MKD", 2);
		$iclISOCurrencyList->add(959, "Gold (one Troy ounce)", "XAU", 0);
		$iclISOCurrencyList->add(410, "South Korean Won", "KRW", 0);
		$iclISOCurrencyList->add(946, "Romanian New Leu", "RON", 2);
		$iclISOCurrencyList->add(949, "New Turkish Lira", "TRY", 2);
		$iclISOCurrencyList->add(532, "Netherlands Antillian Guilder", "ANG", 2);
		$iclISOCurrencyList->add(788, "Tunisian Dinar", "TND", 3);
		$iclISOCurrencyList->add(646, "Rwanda Franc", "RWF", 0);
		$iclISOCurrencyList->add(504, "Moroccan Dirham", "MAD", 2);
		$iclISOCurrencyList->add(174, "Comoro Franc", "KMF", 0);
		$iclISOCurrencyList->add(484, "Mexican Peso", "MXN", 2);
		$iclISOCurrencyList->add(478, "Ouguiya", "MRO", 2);
		$iclISOCurrencyList->add(233, "Kroon", "EEK", 2);
		$iclISOCurrencyList->add(400, "Jordanian Dinar", "JOD", 3);
		$iclISOCurrencyList->add(292, "Gibraltar pound", "GIP", 2);
		$iclISOCurrencyList->add(690, "Seychelles Rupee", "SCR", 2);
		$iclISOCurrencyList->add(422, "Lebanese Pound", "LBP", 2);
		$iclISOCurrencyList->add(232, "Nakfa", "ERN", 2);
		$iclISOCurrencyList->add(496, "Tugrik", "MNT", 2);
		$iclISOCurrencyList->add(328, "Guyana Dollar", "GYD", 2);
		$iclISOCurrencyList->add(970, "Unidad de Valor Real", "COU", 2);
		$iclISOCurrencyList->add(974, "Belarusian Ruble", "BYR", 0);
		$iclISOCurrencyList->add(608, "Philippine Peso", "PHP", 2);
		$iclISOCurrencyList->add(598, "Kina", "PGK", 2);
		$iclISOCurrencyList->add(951, "East Caribbean Dollar", "XCD", 2);
		$iclISOCurrencyList->add(52, "Barbados Dollar", "BBD", 2);
		$iclISOCurrencyList->add(944, "Azerbaijanian Manat", "AZN", 2);
		$iclISOCurrencyList->add(434, "Libyan Dinar", "LYD", 3);
		$iclISOCurrencyList->add(706, "Somali Shilling", "SOS", 2);
		$iclISOCurrencyList->add(950, "CFA Franc BEAC", "XAF", 0);
		$iclISOCurrencyList->add(840, "US Dollar", "USD", 2);
		$iclISOCurrencyList->add(68, "Boliviano", "BOB", 2);
		$iclISOCurrencyList->add(214, "Dominican Peso", "DOP", 2);
		$iclISOCurrencyList->add(818, "Egyptian Pound", "EGP", 2);
		$iclISOCurrencyList->add(170, "Colombian Peso", "COP", 2);
		$iclISOCurrencyList->add(986, "Brazilian Real", "BRL", 2);
		$iclISOCurrencyList->add(961, "Silver (one Troy ounce)", "XAG", 0);
		$iclISOCurrencyList->add(973, "Kwanza", "AOA", 2);
		$iclISOCurrencyList->add(962, "Platinum (one Troy ounce)", "XPT", 0);
		$iclISOCurrencyList->add(414, "Kuwaiti Dinar", "KWD", 3);
		$iclISOCurrencyList->add(604, "Nuevo Sol", "PEN", 2);
		$iclISOCurrencyList->add(702, "Singapore Dollar", "SGD", 2);
		$iclISOCurrencyList->add(862, "Venezuelan bol�var", "VEB", 2);
		$iclISOCurrencyList->add(953, "CFP franc", "XPF", 0);
		$iclISOCurrencyList->add(558, "Cordoba Oro", "NIO", 2);
		$iclISOCurrencyList->add(348, "Forint", "HUF", 2);
		$iclISOCurrencyList->add(948, "WIR Franc ", "CHW", 2);
		$iclISOCurrencyList->add(116, "Riel", "KHR", 2);
		$iclISOCurrencyList->add(956, "European Monetary Unit", "XBB", 0);
		$iclISOCurrencyList->add(156, "Yuan Renminbi", "CNY", 2);
		$iclISOCurrencyList->add(834, "Tanzanian Shilling", "TZS", 2);
		$iclISOCurrencyList->add(997, "", "USN", 2);
		$iclISOCurrencyList->add(981, "Lari", "GEL", 2);
		$iclISOCurrencyList->add(242, "Fiji Dollar", "FJD", 2);
		$iclISOCurrencyList->add(941, "Serbian Dinar", "RSD", 2);
		$iclISOCurrencyList->add(104, "Kyat", "MMK", 2);
		$iclISOCurrencyList->add(84, " Belize Dollar", "BZD", 2);
		$iclISOCurrencyList->add(710, "South African Rand", "ZAR", 2);
		$iclISOCurrencyList->add(760, "Syrian Pound", "SYP", 2);
		$iclISOCurrencyList->add(512, "Rial Omani", "OMR", 3);
		$iclISOCurrencyList->add(324, "Guinea Franc", "GNF", 0);
		$iclISOCurrencyList->add(196, "Cyprus Pound", "CYP", 2);
		$iclISOCurrencyList->add(960, "Special Drawing Rights", "XDR", 0);
		$iclISOCurrencyList->add(716, "Zimbabwe Dollar", "ZWD", 2);
		$iclISOCurrencyList->add(972, "Somoni", "TJS", 2);
		$iclISOCurrencyList->add(462, "Rufiyaa", "MVR", 2);
		$iclISOCurrencyList->add(979, "Mexican Unidad de Inversion (UDI)", "MXV", 2);
		$iclISOCurrencyList->add(860, "Uzbekistan Som", "UZS", 2);
		$iclISOCurrencyList->add(12, "Algerian Dinar", "DZD", 2);
		$iclISOCurrencyList->add(332, "Haiti Gourde", "HTG", 2);
		$iclISOCurrencyList->add(963, "Code reserved for testing purposes", "XTS", 0);
		$iclISOCurrencyList->add(32, "Argentine Peso", "ARS", 2);
		$iclISOCurrencyList->add(642, "Romanian Leu", "ROL", 2);
		$iclISOCurrencyList->add(984, "Bolivian Mvdol (Funds code)", "BOV", 2);
		$iclISOCurrencyList->add(440, "Lithuanian Litas", "LTL", 2);
		$iclISOCurrencyList->add(480, "Mauritius Rupee", "MUR", 2);
		$iclISOCurrencyList->add(426, "Loti", "LSL", 2);
		$iclISOCurrencyList->add(262, "Djibouti Franc", "DJF", 0);
		$iclISOCurrencyList->add(886, "Yemeni Rial", "YER", 2);
		$iclISOCurrencyList->add(748, "Lilangeni", "SZL", 2);
		$iclISOCurrencyList->add(192, "Cuban Peso", "CUP", 2);
		$iclISOCurrencyList->add(548, "Vatu", "VUV", 0);
		$iclISOCurrencyList->add(360, "Rupiah", "IDR", 2);
		$iclISOCurrencyList->add(51, "Armenian Dram", "AMD", 2);
		$iclISOCurrencyList->add(894, "Kwacha", "ZMK", 2);
		$iclISOCurrencyList->add(90, "Solomon Islands Dollar", "SBD", 2);
		$iclISOCurrencyList->add(132, "Cape Verde Escudo", "CVE", 2);
		$iclISOCurrencyList->add(999, "No currency", "XXX", 0);
		$iclISOCurrencyList->add(524, "Nepalese Rupee", "NPR", 2);
		$iclISOCurrencyList->add(203, "Czech Koruna", "CZK", 2);
		$iclISOCurrencyList->add(44, "Bahamian Dollar", "BSD", 2);
		$iclISOCurrencyList->add(96, "Brunei Dollar", "BND", 2);
		$iclISOCurrencyList->add(50, "Bangladeshi Taka", "BDT", 2);
		$iclISOCurrencyList->add(404, "Kenyan Shilling", "KES", 2);
		$iclISOCurrencyList->add(947, "WIR Euro ", "CHE", 2);
		$iclISOCurrencyList->add(964, "Palladium (one Troy ounce)", "XPD", 0);
		$iclISOCurrencyList->add(398, "Tenge", "KZT", 2);
		$iclISOCurrencyList->add(352, "Iceland Krona", "ISK", 2);
		$iclISOCurrencyList->add(64, "Ngultrum", "BTN", 2);
		$iclISOCurrencyList->add(533, "Aruban Guilder", "AWG", 2);
		$iclISOCurrencyList->add(230, "Ethiopian Birr", "ETB", 2);
		$iclISOCurrencyList->add(800, "Uganda Shilling", "UGX", 2);
		$iclISOCurrencyList->add(968, "Surinam Dollar", "SRD", 2);
		$iclISOCurrencyList->add(882, "Samoan Tala", "WST", 2);
		$iclISOCurrencyList->add(454, "Kwacha", "MWK", 2);
		$iclISOCurrencyList->add(985, "Zloty", "PLN", 2);
		$iclISOCurrencyList->add(124, "Canadian Dollar", "CAD", 2);
		$iclISOCurrencyList->add(776, "Pa'anga", "TOP", 2);
		$iclISOCurrencyList->add(208, "Danish Krone", "DKK", 2);
		$iclISOCurrencyList->add(108, "Burundian Franc", "BIF", 0);
		$iclISOCurrencyList->add(764, "Baht", "THB", 2);
		$iclISOCurrencyList->add(458, "Malaysian Ringgit", "MYR", 2);
		$iclISOCurrencyList->add(364, "Iranian Rial", "IRR", 2);
		$iclISOCurrencyList->add(600, "Guarani", "PYG", 0);
		$iclISOCurrencyList->add(977, "Convertible Marks", "BAM", 2);
		$iclISOCurrencyList->add(446, "Pataca", "MOP", 2);
		$iclISOCurrencyList->add(780, "Trinidad and Tobago Dollar", "TTD", 2);
		$iclISOCurrencyList->add(703, "Slovak Koruna", "SKK", 2);
		$iclISOCurrencyList->add(958, "European Unit of Account 17 (E.U.A.-17)", "XBD", 0);
		$iclISOCurrencyList->add(430, "Liberian Dollar", "LRD", 2);
		$iclISOCurrencyList->add(191, "Croatian Kuna", "HRK", 2);
		$iclISOCurrencyList->add(694, "Leone", "SLL", 2);
		$iclISOCurrencyList->add(756, "Swiss Franc", "CHF", 2);
		$iclISOCurrencyList->add(969, "Malagasy Ariary", "MGA", 0);
		$iclISOCurrencyList->add(270, "Dalasi", "GMD", 2);
		$iclISOCurrencyList->add(418, "Kip", "LAK", 2);
		$iclISOCurrencyList->add(516, "Namibian Dollar", "NAD", 2);
		$iclISOCurrencyList->add(392, "Japanese yen", "JPY", 0);
		$iclISOCurrencyList->add(320, "Quetzal", "GTQ", 2);
		$iclISOCurrencyList->add(554, "New Zealand Dollar", "NZD", 2);
		$iclISOCurrencyList->add(578, "Norwegian Krone", "NOK", 2);
		$iclISOCurrencyList->add(376, "New Israeli Shekel", "ILS", 2);
		$iclISOCurrencyList->add(957, "European Unit of Account 9 (E.U.A.-9)", "XBC", 0);
		$iclISOCurrencyList->add(498, "Moldovan Leu", "MDL", 2);
		$iclISOCurrencyList->add(998, "", "USS", 2);
		$iclISOCurrencyList->add(955, "European Composite Unit (EURCO)", "XBA", 0);
		$iclISOCurrencyList->add(344, "Hong Kong Dollar", "HKD", 2);
		$iclISOCurrencyList->add(417, "Som", "KGS", 2);
		$iclISOCurrencyList->add(858, "Peso Uruguayo", "UYU", 2);
		$iclISOCurrencyList->add(60, "Bermudian Dollar ", "BMD", 2);
		$iclISOCurrencyList->add(682, "Saudi Riyal", "SAR", 2);
		$iclISOCurrencyList->add(643, "Russian Ruble", "RUB", 2);
		$iclISOCurrencyList->add(470, "Maltese Lira", "MTL", 2);
		$iclISOCurrencyList->add(340, "Lempira", "HNL", 2);
		$iclISOCurrencyList->add(72, "Pula", "BWP", 2);
		$iclISOCurrencyList->add(368, "Iraqi Dinar", "IQD", 3);
		$iclISOCurrencyList->add(188, "Costa Rican Colon", "CRC", 2);
		$iclISOCurrencyList->add(144, "Sri Lanka Rupee", "LKR", 2);
		$iclISOCurrencyList->add(752, "Swedish Krona", "SEK", 2);
		$iclISOCurrencyList->add(136, "Cayman Islands Dollar", "KYD", 2);
		$iclISOCurrencyList->add(8, "Lek", "ALL", 2);
		$iclISOCurrencyList->add(48, "Bahraini Dinar", "BHD", 3);
		$iclISOCurrencyList->add(795, "Manat", "TMM", 2);
		$iclISOCurrencyList->add(938, "Sudanese Pound", "SDG", 2);
		$iclISOCurrencyList->add(590, "Balboa", "PAB", 2);
		$iclISOCurrencyList->add(152, "Chilean Peso", "CLP", 0);
		$iclISOCurrencyList->add(980, "Hryvnia", "UAH", 2);
		$iclISOCurrencyList->add(428, "Latvian Lats", "LVL", 2);
		$iclISOCurrencyList->add(288, "Cedi", "GHS", 2);
		$iclISOCurrencyList->add(978, "Euro", "EUR", 2);
		$iclISOCurrencyList->add(976, "Franc Congolais", "CDF", 2);
		$iclISOCurrencyList->add(586, "Pakistan Rupee", "PKR", 2);
		$iclISOCurrencyList->add(408, "North Korean Won", "KPW", 2);
		$iclISOCurrencyList->add(388, "Jamaican Dollar", "JMD", 2);
		$iclISOCurrencyList->add(990, "Unidades de formento", "CLF", 0);
		$iclISOCurrencyList->add(971, "Afghani", "AFN", 2);
		$iclISOCurrencyList->add(975, "Bulgarian Lev", "BGN", 2);
		$iclISOCurrencyList->add(36, "Australian Dollar", "AUD", 2);
		$iclISOCurrencyList->add(238, "Falkland Islands Pound", "FKP", 2);
		$iclISOCurrencyList->add(901, "New Taiwan Dollar", "TWD", 2);
		$iclISOCurrencyList->add(784, "United Arab Emirates dirham", "AED", 2);
		return $iclISOCurrencyList;
	}	
}	